version: "3.4"
services:
  db:
    image: hub.artifactory.gcp.anz/postgres:12.4-alpine
    environment:
      POSTGRES_DB: countrydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"